### ISSUE TITLE
你好，虫师， 如果想要在你封装的基础上实现POM ，请告知如何实现 

### ISSUE THREAD

**Issue by skyaiolos** [defnngj/pyse#7]
你好，虫师， ， 在你的封装基础上如何运用 POM 。
请赐教！

**Comment by defnngj** [comment]
新增了 POM 的 demo ，自己去看吧！
https://github.com/defnngj/pyse/blob/master/demo/test_case_po.py

**Comment by skyaiolos** [comment]
谢谢你 ！
